general {
  lock_cmd = loginctl lock-session
  before_sleep_cmd = loginctl lock-session
}

listener {
  timeout = 300
  on-timeout = brightnessctl -s set 5%- 
  on-resume = brightnessctl -r
}

listener {
  timeout = 600
  on-timeout = hyprlock
  on-resume =  hyprctl dispatch dpms on
}

listener {
  timeout = 1000
  on-timeout = systemctl suspend-then-hibernate
}
